### ISSUE TITLE
using cs,which already exists

### ISSUE THREAD

**Issue by AlexandrKozlovskiy** [latex3/pdfresources#10]
When i try to compile some document,which use pdfresources package (branch master),i get an error:

Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
("C:/Program Files/MiKTeX/tex/latex/base/size10.clo"))
("C:/Program Files/MiKTeX/tex/latex/tagpdf/tagpdf.sty"
("C:/Program Files/MiKTeX/tex/latex/pdfresources/pdfresources.sty"
("C:/Program Files/MiKTeX/tex/latex/l3packages/xparse/xparse.sty"
("C:/Program Files/MiKTeX/tex/latex/l3kernel/expl3.sty"
("C:/Program Files/MiKTeX/tex/latex/l3backend/l3backend-pdfmode.def"))
("C:/Program Files/MiKTeX/tex/latex/l3packages/xparse/xparse-generic.tex"))
("C:/Program Files/MiKTeX/tex/latex/l3experimental/l3pdf/l3pdf.sty")
("C:/Program Files/MiKTeX/tex/generic/atbegshi/atbegshi.sty"
("C:/Program Files/MiKTeX/tex/generic/infwarerr/infwarerr.sty")
("C:/Program Files/MiKTeX/tex/generic/ltxcmds/ltxcmds.sty")
("C:/Program Files/MiKTeX/tex/generic/iftex/iftex.sty"))
("C:/Program Files/MiKTeX/tex/latex/zref/zref-lastpage.sty"
("C:/Program Files/MiKTeX/tex/latex/zref/zref-base.sty"
("C:/Program Files/MiKTeX/tex/generic/kvsetkeys/kvsetkeys.sty")
("C:/Program Files/MiKTeX/tex/generic/kvdefinekeys/kvdefinekeys.sty")
("C:/Program Files/MiKTeX/tex/generic/pdftexcmds/pdftexcmds.sty")
("C:/Program Files/MiKTeX/tex/generic/etexcmds/etexcmds.sty")
("C:/Program Files/MiKTeX/tex/latex/auxhook/auxhook.sty"))
("C:/Program Files/MiKTeX/tex/latex/zref/zref-abspage.sty")
("C:/Program Files/MiKTeX/tex/latex/atveryend/atveryend.sty"))

! LaTeX3 Error: Control sequence \__pdf_backend_pageobject_ref:n already
(LaTeX3)        defined.

For immediate help type H <return>.
 ...

l.211   }

May be for latest latex i should use splitting branch of this package? In fact i use this package no direct,but via tagpdf package,to test branch splitting of this package. Thanks.

**Comment by u-fischer** [comment]
the master branch is not up-to-date. Currently both in tagpdf and pdfresources the splitting branches should be used (but I plan to merge this back in the near future).

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer But now i get an error,that cs \NewDocumentCommand
                      \DeclareDocumentMetaData { m } is undefined.

**Comment by u-fischer** [comment]
Then you probably don't have the new latex which includes xparse. Update, this all needs a quite recent latex.

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer but in miktex console i haven't any updates. In log during compilation of document i have:

lualatex: security risk: running with elevated privileges
initexmf: security risk: running with elevated privileges
initexmf: security risk: running with elevated privileges
This is LuaHBTeX, Version 1.12.0 (MiKTeX 20.7)
 restricted system commands enabled.

**Comment by u-fischer** [comment]
Sorry this doesn't say which latex you have.

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer but i have lualatex 1.12.0. How i can check correct version of latex and update it?

**Comment by u-fischer** [comment]
Check the log file, it should contain something like latex 2020-10-01

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer Ok,in log i have: LaTeX2e <2020-02-02> patch level 5

**Comment by FrankMittelbach** [comment]
> @u-fischer but i have lualatex 1.12.0. How i can check correct version of latex and update it?

@AlexandrKozlovskiy  sigh. This is really a very basic question. If you need help on such things you should really not try and use cutting edge development code from git repositories but consider sticking  to distributed versions.

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer ok,but why miktex not propose to me update latex?

**Comment by AlexandrKozlovskiy** [comment]
May be latex possible update only manually,not via miktex console?

**Comment by AlexandrKozlovskiy** [comment]
@u-fischer i reinstalled miktex and get update of latex and now all ok. Yes,i still get an error in tagpdf package in branch splitting,that pdf management is no active,but it not topic for tagpdf,so we can close this discussion,and,if you want,move to tagpdf repository,because i want very much test splitting branch of this package.
