### ISSUE TITLE
the \transwipe command no longer seems to accept optional arguments 

### ISSUE THREAD

**Issue by numaxx21** [latex3/pdfresources#29]
```
\RequirePackage{pdfmanagement-testphase}%
\DocumentMetadata{} % activate the PDF management (with options)
\documentclass{beamer}

\setbeamertemplate{background}[grid]
\begin{document}
\begin{frame}
%\transwipe[direction=0]
\transwipe[duration=3]
%\transwipe 
\end{frame} 
\end{document}
```
This code  with  `\transwipe[duration=3]` don't works but with  `\transwipe`, it works.

**Comment by u-fischer** [comment]
The new hyperref driver used with the pdfmanagement has extended support for transitions. There are now more keys to set them. But this lead to a different syntax and so beamer will need adjustments here to correctly translate its options.  You can set transitions with hypersetup 

      \hypersetup{pdfpagetransition={style=Fly,duration=2,direction=90,opaque=false}}

Your example would need probably 

     \hypersetup{pdfpagetransition={style=Wipe,duration=3}}

**Comment by u-fischer** [comment]
I opened a pull request for beamer https://github.com/josephwright/beamer/pull/765.  While testing this I found also a small typo  in the pdfresource, which breaks some of the transitions, the next version will resolve this.
