### ISSUE TITLE
New field in hyperref (specific for pdf forms)

### ISSUE THREAD

**Issue by gildasprevost** [latex3/pdfresources#31]
![image](https://user-images.githubusercontent.com/2934482/161764771-2db29a60-863e-4842-a396-7851ad11f066.png)

**Comment by u-fischer** [comment]
I would need small (!) example pdf with such a field so that I can check how it is encoded.

**Comment by gildasprevost** [comment]
Yes of course!
[Exemple.pdf](https://github.com/latex3/pdfresources/files/8418710/Exemple.pdf)

**Comment by u-fischer** [comment]
As I wrote here https://texnique.fr/osqa/questions/10834/formulaire-pdf-avec-image-modifiable this is only a button field with a javascript action. A simple version looks like this

~~~~
\RequirePackage{pdfmanagement-testphase} % not needed with latex-dev
\DocumentMetadata{uncompress}
\documentclass{article}
\usepackage{l3pdffield-testphase}
\begin{document}
\ExplSyntaxOn
  \group_begin:
  \tl_set:Nn\l_tmpa_tl{event.target.buttonImportIcon();}
  \pdf_object_unnamed_write:nx{stream}{{}{\exp_not:o{\l_tmpa_tl}}}
  \pdfannot_dict_put:nnx{widget}{A}{<</S/JavaScript /JS~\pdf_object_ref_last:>>}
  \pdffield_pushbutton:n{name=bild,width=10cm,height=8cm,MK/TP=1}
  \group_end:
 \ExplSyntaxOff
\end{document}
~~~~

Border, colors etc can be adjusted with the existing methods.

The same should be possible with the existing \PushButton field of hyperref.

**Comment by gildasprevost** [comment]
That's perfect, thank you very much for this solution!
