### ISSUE TITLE
Metadata item "pdfaid:rev" causes non-conforming PDF/A files

### ISSUE THREAD

**Issue by marcpenninga** [latex3/pdfresources#33]
The file "hyperxmp-patches-tmp-ltx.sty" defines a metadata item "pdfaid:rev", according to a source code comment to support PDF/A-4. However, this metadata item is undefined (and hence forbidden) in PDF/A-1, A-2 and A-3, so the current code leads to non-conforming pdf output. In fact, even the pdf documents in this repo, which claim to conform to PDF/A-2b, are rejected by validation tools such as VeraPDF and 3-Heights because of this issue. Removing the definition of pdfaid:rev produces valid PDF/A files.

**Comment by u-fischer** [comment]
Thanks, I have adapted the code so it inserts pdfaid-rev only for pdf/A-4.
