### ISSUE TITLE
`hyperref`'s `breaklinks` option honored with `lualatex` but not with `pdflatex`

### ISSUE THREAD

**Issue by dbitouze** [latex3/pdfresources#34]
The following MWE shows that the `hyperref`'s `breaklinks` option is honored with `lualatex` but not with `pdflatex`:
- with `lualatex`, the URL is broken at the line (and page) break (as expected),
- with `pdflatex`, the URL is _not_ broken at the line (and page) break.
```latex
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}

\documentclass{article}
\usepackage{lipsum}
\usepackage[base]{babel}
\usepackage[breaklinks]{hyperref}
\begin{document}
\lipsum[1-5]
Fusce mauris. Vestibulum luctus
\url{https://www.foofoofoofoofoofoofoofoofoofoo.org}
\end{document}
```
BTW, if `pdfmanagement-testphase` is not loaded, the issue https://github.com/latex3/hyperref/issues/54 occurs, which tends to prove that the new LaTeX PDF management is well on its way to fixing it! :smile:

**Comment by u-fischer** [comment]
The option breaklinks does nothing at all with pdftex or luatex (and not much with other drivers too, imho the only driver with some code here is hdviwind.def).

You see simply some difference between paragraph building of the engines.  With this for example both break the link:

~~~~
\documentclass{article}
\usepackage{hyperref}
\begin{document}

xxxxxxxxxxxxxxxxxx  Fusce mauris. Vestibulum xxxxxxx
\url{https://www.foofoofoofoofoofoofoofoofoofoo.org} 
\end{document}
~~~~
