### ISSUE TITLE
Local assignment to global `\g__pdfmanagement_firstaid_fontspec_bool`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/pdfresources#36]
https://github.com/latex3/pdfresources/blob/2dd8428183bb81c4907c9e72ac8509b597748ec3/pdfmanagement-firstaid.dtx#L99-L105

Relevant code is introduced in https://github.com/latex3/pdfresources/commit/1bec95402c6af2793a370a0dcbf6ac9502792483, then reordered by https://github.com/latex3/pdfresources/commit/324e2823776b1583171c09099f666aea126b54d5.

This causes latex2e's automated testing fails, for example https://github.com/muzimuzhi/latex2e/actions/runs/2523909701 . 

Edit: Looks like `\g__pdfmanagement_firstaid_fontspec_bool` need not be global.

**Comment by u-fischer** [comment]
yes thanks. Marcel found that already. It should be correct in develop.

**Comment by muzimuzhi** [comment]
Sorry I didn't check the develop branch. If so I will find #35 that already fixed this issue.
