### ISSUE TITLE
Request for more project documentation

### ISSUE THREAD

**Issue by car222222** [latex3/pdfresources#4]
My first request is for an Overview of the breadth of this project.

This could later be developed further, providing details of the coverage and its distinct parts, hopefully with references to documents from the PDF community and descriptions using  their phraseology. 

Thanks!

**Comment by car222222** [comment]
Second request: develop these ideas into generic functions to create and manipulate all types if pdf objects (where “all” is suitably defined:-).

I realize that this is ill-defined and that I should provide detailed specs, but this month is too short, or the margin is too small, . . . !

**Comment by u-fischer** [comment]
> Second request: develop these ideas into generic functions to create and manipulate all types of pdf objects

The generic functions are already there, either in this style or in l3pdf. What are you missing?

**Comment by car222222** [comment]
Good. I was clearly missing l3pdf (not being aware of it or its contents).

So now I need t hunt for these generic commands to see if they are sufficiently generic to satisfy Frank’s criteria :-).  Do they at least have names that indicate that they are generic?

**Comment by josephwright** [comment]
@car222222 I think we need to know what exactly you are after: the `l3pdf` code is all pretty basic ... it's about building up objects and the like

**Comment by car222222** [comment]
True.  I only just discovered l3pdf.  I have still only looked briefly at it.

I will look further and send comments on it in the appropriate place.

**Comment by car222222** [comment]
One year on: despite its now being in the kernel, l3pdf is very quirky.  And so going forward it is not clear how it should be revised and developed further.

**Comment by u-fischer** [comment]
The project is documentated, and if something is missing a new issue should be created.
