### ISSUE TITLE
pdfmanagement-testphase and include svg

### ISSUE THREAD

**Issue by martijor** [latex3/pdfresources#46]
Hello.

pdfmanagement-testphase doesn't say anything about incompatibilities with the svg package.
I have a document which compiles just fine with Lualatex :
```latex
\documentclass[11pt,a4paper]{article}
\usepackage{svg}

\begin{document}
\includesvg{some svg.svg}
\end{document}
```

However, adding DocumentMetadata{} prevents it from compiling :
```latex
\DocumentMetadata{}
\documentclass[11pt,a4paper]{article}
\usepackage{svg}

\begin{document}
\includesvg{some svg.svg}
\end{document}
```

Throws an error :

> ! File ended while scanning use of \__pdfmanagement_patch_pgfextgs:w.<inserted text>\par<> test.texI suspect you have forgotten a `}', causing meto read past where you wanted me to stop.

Tried on a Windows 11 platform with up to date Miktex packages and LuaLatex.

**Comment by u-fischer** [comment]
miktex has updated the package and the example compiles fine.
