### ISSUE TITLE
`\DocumentMetadata{}` disables stream uncompression for dvips

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/pdfresources#48]
`l3build`'s [`regression-test.tex`](https://github.com/latex3/l3build/blob/305f2106a0f27bfdf12ae0f35149f7bab5de12e3/l3build.dtx#L2464-L2469) sets
```tex
  \special{%
      ps: /setdistillerparams
      where
        {pop << /CompressPages false /CompressStreams false >> setdistillerparams}
      if
    }%
```
 to uncompress pdf generated by `ps2pdf`.

But if `\DocumentMetadata{}` is used, the `/Type/Metadata` object in pdf is no longer uncompressed and one has to pass `-dCompressStreams=false` to `ps2pdf` to re-enable uncompression (https://github.com/latex3/l3build/pull/278#issuecomment-1441325092). See an example diff [here](https://github.com/latex3/l3build/pull/278/files/35d2821edc7152ad451f5cda918d49dedcdc8978..6654d27398e0b6e1c8e44d6d775a7c10d50d4628)

The `.tpf` files in current repo's directory [`testfiles-dvips`](https://github.com/latex3/pdfresources/tree/main/testfiles-dvips) also reflect this difference. Thus I suppose this is a known problem/limitation.

```tex
% \DocumentMetadata{}
\input regression-test\relax
\documentclass{article}

\begin{document}
text
\end{document}
```

From the intermediate ps files, it seems with `\DocumentMetadata{}` the corresponding special is inserted too late:
```diff
 %%Page: 1 1
-TeXDict begin 1 0 bop 515 440 a
+TeXDict begin 1 0 bop -600 -600 a
+ [{ThisPage}<<>> /PUT pdfmark
+ -600 -600 a 515 440
+a
  /setdistillerparams where {pop << /CompressPages false /CompressStreams
 false >> setdistillerparams} if
```

**Comment by u-fischer** [comment]
Without `\DocumentMetadata` you get the xmp-metadata added by Ghostscript; with  `\DocumentMetadata` the one added by the pdfmanagement code. Ghostscript honors then that there are user metadata and doesn't add its own, but it offers no option to add it as an uncompressed stream (I had a discussion about that https://bugs.ghostscript.com/show_bug.cgi?id=705962) and imho it doesn't react to the `/setdistillerparams` either. The only way to uncompress it is to pass the options (in the few tests I have I normally use `\DocumentMetadata{xmp=false}` as I didn't want to bother with this).

**Comment by muzimuzhi** [comment]
It seems https://bugs.ghostscript.com/show_bug.cgi?id=705962 only tells there's no way to uncompress the xmp stream solely, but didn't clearly say the `/setdistillerparams` setting is not honored (on xmp stream added by the pdfmanagement code). Is it?

**Comment by u-fischer** [comment]
I retried. Even if I put the special in the background hook (where it is then before the pdfmark) the XMP stays compressed. 

~~~~
\AddToHook{shipout/background}{ \special{%
      ps: /setdistillerparams
      where
        {pop << /CompressPages false /CompressStreams false >> setdistillerparams}
      if
    }}%
\input regression-test\relax
\DocumentMetadata{}
\showoutput
\documentclass{article}

\begin{document}
text
\end{document}
~~~~

So I think there is nothing one can do unless ghostscript changes something and I'm closing here for now.
