### ISSUE TITLE
ZUGfeRD prototype using l3pdfmeta

### ISSUE THREAD

**Issue by t-b** [latex3/pdfresources#49]
In DTK 1/2023 is an article about adding XMP metadata in LaTeX. And in that article the authors state 

> there exists a prototype implementing the ZUGfeRD 2.2 standard

is that available publically already?

As I'm using lualatex for writing invoices and will have to supply machine readable invoices in the future, I would be interested in that.

**Comment by TeXhackse** [comment]
You might want to have a look at [experiments/factur-x-bills](https://github.com/latex3/pdfresources/tree/main/experiments/factur-x-bills)

**Comment by u-fischer** [comment]
I don't have good internet currently, so can answer questions only next week

**Comment by u-fischer** [comment]
As @TeXhackse  wrote, there is a short prototype in the experiments folder. It needs a bit polishing up, but I would need more testfiles and feedback first. 

Note that is only handles the inclusion of the xml into the PDF, the generation of the xml and the invoice data should imho better be done by some sensible accounting software (I couldn't experiment with this, as I couldn't find a suitable free software).

**Comment by t-b** [comment]
@u-fischer Thanks for the explanation. My accounting software does not create suitable XML files for inclusion, so I would need to come up with a custom solution anway once ZUGfeRD becomes more widespread/mandatory.

**Comment by u-fischer** [comment]
there is a new package on ctan, zugferd which offers support. So I'm closing here.
