### ISSUE TITLE
! LaTeX Error: File `l3bitset.sty' not found.

### ISSUE THREAD

**Issue by yrogge** [latex3/pdfresources#60]
Using pdfmanagement 2023-11-17 v0.96c with LuaLaTex.
After last CTAN update (2022-12-08) of l3kernel (and l3experimental), function \bitset_new:Nn used at line 1085 in pdfmanagement-testphase.ltx can no more be found.
No compilation can be performed anymore.
Issue seems to be related to source file l3bitset.sty

**Comment by u-fischer** [comment]
Yes sorry I already uploaded a new pdfmanagement to resolve this. As a work around put an empty l3bitset.sty somewhere in your path.

**Comment by yrogge** [comment]
Thanks!
I have already used this trick, and I'm waiting on your patch.
This issue was to give you some immediate feedback.
