### ISSUE TITLE
undefined page references in docs

### ISSUE THREAD

**Issue by mbertucci47** [latex3/pdfresources#65]
Same issue as https://github.com/latex3/latex3/issues/1345 but for the pdfmanagement docs. The list of command entries giving undefined references is below.

### l3pdfmeta
- `pdfaid~(schema)`
- `pdfuaid~(schema)`
- `pdfxid~(schema)`
- `prism~(schema)`
- `\__pdfmeta_xmp_build_pdf:`, `Producer/pdfproducer`, and `PDFversion`
- `\__pdfmeta_xmp_build_xmp:`, `CreatorTool/pdfcreator`, and `BaseUrl/baseurl`
- `\__pdfmeta_xmp_build_dc:` and others
- `\__pdfmeta_xmp_build_prism:`, `complianceProfile`, and `prism:subtitle/pdfsubtitle`

### l3pdffield
- `AA/Fo` and others

### l3pdffield-radiobutton
- `\__pdffield_radio_default_appearances:` and others

### l3pdffield-pushbutton
- `\__pdffield_pushbutton_default_appearances:` and others
- `\pdffield_pushbutton:n`

### l3pdffield-choice
- `type`

### l3pdffield-checkbox
- `\__pdffield_checkbox_default_appearances:`, `pdffield/checkbox/default/Yes`,
and `pdffield/checkbox/default/Off`

**Comment by u-fischer** [comment]
I finally did the corrections ...
