### ISSUE TITLE
Hyperref hypersetup doesn't expand the argument of pdfauthor

### ISSUE THREAD

**Issue by BlairDHall** [latex3/pdfresources#72]
Would it be possible for hypersetup to expand the argument of pdfauthor? At present `\hypersetup{ pdfauthor={Me, Bobby McGee} }` will correctly set two authors, but 
```
\newcommand{\names}{Me, Bobby McGee}
\hypersetup{ pdfauthor={\names} }
```
just combines them in one string,

See [stackexchange.com question 722124](https://tex.stackexchange.com/questions/722124/supplying-data-to-hyperrefs-pdfauthor-different-command-types-give-different-r?noredirect=1#comment1796606_722124) for details.

**Comment by u-fischer** [comment]
a new version has been sent to ctan.
