### ISSUE TITLE
How to set document title and author with pdf-management?

### ISSUE THREAD

**Issue by Mankka** [latex3/pdfresources#73]
I'm trying out the latest pdf-management code on an up to date texlive 2024 and I'm asking for best practises. I have been using the following code to set pdf title and author:
```latex
\documentclass{article}
\usepackage[pdfusetitle=true]{hyperref}

\title{My Title}
\author{My Name}

\begin{document}
\maketitle
\end{document}
```
It works with both `lualatex` and `lualatex-dev`, and `pdfinfo` returns
```
Title:           My Title
Subject:         
Keywords:        
Author:          My Name
Creator:         LaTeX with hyperref
Producer:        LuaTeX-1.18.0
...
```
When I add `DocumentMetadata` the above no long works, and I use the following workaround to set title and author:
```latex
\DocumentMetadata
{
  testphase = {phase-III},
  pdfversion = 2.0,
  %pdfstandard=ua-2,
  lang=en
}
\documentclass{article}

\usepackage{hyperref}
\hypersetup{
  pdftitle = {My Title},
  pdfauthor = {My Name}
}

\author{\GetDocumentProperties{hyperref/pdfauthor}}
\title{\GetDocumentProperties{hyperref/pdftitle}}

\begin{document}
\maketitle
\end{document}
```
This again works on both `lualatex` and `lualatex-dev` and has the following `pdfinfo`:
```
Title:           My Title
Author:          My Name
Creator:         LaTeX with hyperref
Producer:        luahbtex-1.18.0
Custom Metadata: yes
Metadata Stream: yes
Tagged:          yes
...
```
**Is this a recommended way to set the title and author?**
If I uncomment the line `pdfstandard=ua-2`, the `pdfinfo` is
```
Custom Metadata: no
Metadata Stream: yes
Tagged:          yes
...
```
**Is this expected? Where can I learn more about how to use the `DocumentMetadata`?**

**Comment by u-fischer** [comment]
You can also use the title testphase module. It will try to pick up the value from the title. But be aware that this relies on a specific definition of `\author` and `\title`. If you use a class or a package which redefines this commands again to e.g. add optional arguments for affiliations or similar it will break (that is the main reason why pdfusetitle is disabled by default: it doesn't work reliably). Note also that neither title and author should then contains things that the PDF doesn't like, so do not add colors or so ... 

~~~~
\DocumentMetadata
{
  testphase = {phase-III,title},
  pdfversion = 2.0,
  %pdfstandard=ua-2,
  lang=en
  ,uncompress
}
\documentclass{article}

\usepackage{hyperref}

\author{Author}
\title{my Title}

\begin{document}
\maketitle
\end{document}
~~~~

**Comment by Mankka** [comment]
Thank you! Now I actually see the `title` option in the documentation. And I guess the `pdfstandard = ua-2` is not implemented yet, for `pdfversion = 1.7`, `pdfstandard = A-2u` works just fine.

**Comment by FrankMittelbach** [comment]
it will nver be implemented. PDF/UA-2 is based on PDF-2.0 and requires therefore pdfversion=2.0

**Comment by FrankMittelbach** [comment]
but I guess there should be some checks that incompatible requirements, e.g. 1.7 + ua-2 are flagged at least ass a warning but perhaps even as an error.

**Comment by u-fischer** [comment]
> If I uncomment the line pdfstandard=ua-2, the pdfinfo is
> And I guess the pdfstandard = ua-2 is not implemented yet,

ua-2 is implemented, and yes it suppresses the Info dictionary (that is required in this standard).

@FrankMittelbach 

> but I guess there should be some checks that incompatible requirements, e.g. 1.7 + ua-2

Yes, I can add a warning (A-4 issues a warning if used with pdf 1.7 but here I forgot to add that.)
