### ISSUE TITLE
PDF/A and ocgx2 layers broken

### ISSUE THREAD

**Issue by ReubenM** [latex3/pdfresources#77]
From what I've read, OCGs are allow in PDF/A starting with PDF/A-2. I'm attempting to be able to produce PDF output using pdflatex that incorporates OCG layers and validates against veraPDF.

I created an initial issue with ocgx2, and some changes were made that allow output to pass PDF/A-3b validation:
https://gitlab.com/agrahn/ocgx2/-/issues/21

However, with the pdfstandard argument set, I'm not able to manipulate the layer visibility. (I'm testing this with FireFox's builtin pdf.js viewer that has a size panel for viewing and toggling ocg layers) I suspect something in pdfmanagement is breaking that functionality somehow, or perhaps some sort of integration between ocgx2 and pdfmanagement is needed. The ocg layers work fine when the pdfstandard argument is removed and a plain PDF-1.7 document is created.

**Comment by u-fischer** [comment]
Please add a complete, small document that can be used for a test.

**Comment by u-fischer** [comment]
I removed the requirement that suppressed the OCProperties Catalog entry for pdf/a-2 onwards. Until this is released you can use this work around

~~~~
\DocumentMetadata{lang=en,pdfversion=1.7}
\ExplSyntaxOn
\prop_gremove:cn
  { g__pdfmeta_standard_pdf/A-3B_prop }
  { Catalog_no_OCProperties }
\ExplSyntaxOff
\DocumentMetadata{pdfstandard=a-3b}
~~~~

But I think that is not enough. verapdf now complains about a missing Name key and a AS key that shouldn't be there. But this is something ocgs should address.

**Comment by ReubenM** [comment]
```tex
\DocumentMetadata{%
    pdfstandard=A-3b,
    pdfversion=1.7,
}

\documentclass[letter]{article}

\usepackage[tikz]{ocgx2}
\usepackage{lipsum}

\AddToHook{shipout/background}{%
    \setlength\unitlength{\paperheight}%
    \begin{ocg}[printocg=never,viewocg=ifvisible]{Semi Transparent Blue Box}{box}{false}%
        {\tikz[remember picture,overlay] \node[fill=blue!40!white, draw=black, shape=rectangle, minimum width=5cm, minimum height=5cm, anchor=center] at (current page.center) {};}%
    \end{ocg}%
}

\begin{document}
	\lipsum[1-20]
\end{document}

```

**Comment by ReubenM** [comment]
oops, didn't see you had already fixed it. I'll follow up on the new changes needed in ocgx2.

**Comment by agrahn** [comment]
> I removed the requirement that suppressed the OCProperties Catalog entry for pdf/a-2 onwards. Until this is released you can use this work around
> 
> ```
> \DocumentMetadata{lang=en,pdfversion=1.7}
> \ExplSyntaxOn
> \prop_gremove:cn
>   { g__pdfmeta_standard_pdf/A-3B_prop }
>   { Catalog_no_OCProperties }
> \ExplSyntaxOff
> \DocumentMetadata{pdfstandard=a-3b}
> ```
> 
> But I think that is not enough. verapdf now complains about a missing Name key and a AS key that shouldn't be there. But this is something ocgs should address.

@u-fischer  : As I understand it, PDF/A-2b forbids OCGs entirely, and PDF/A-3b admits them partially: With the latter, the `OCProperties` dict and its sub-dict `D` taking the default OC configuration are allowed again, but the `AS` entry with the array of usage application dictionaries below `D` is still forbidden. How can I suppress a specific entry down in the `Catalog` hierarchy for a specific PDF/A sub-standard? (The `AS` array is needed, e. g.,  for ocg colourlinks, so I cannot do away with it completely.)

**Comment by u-fischer** [comment]
@agrahn As far as I can see (by testing with verapdf, I don't own the standards and don't want to spent my money on them), `/OCProperties` is allowed from PDF/A-2 onwards. That is something the pdfmanagement can test and handle (by suppressing the key in PDF/A-1).

`/AS` inside the `/OCProperties /D` key is not allowed with pdf/A-2 and pdf/A-3 but seems to be allowed in pdf/A-4. I added a test here. So after the next pdfmanagement update you can do

~~~~
\pdfmeta_standard_verify:nTF{Catalog_OCProperties_no_AS}
  {code if AS is allowed}{code if AS is not allowed}
~~~~

verapdf complains also a missing `/Name` key (also in pdf/A-4)

~~~~
Each optional content configuration dictionary that forms the value of the D key, or that is an element in the array that forms the value of the Configs key in the OCProperties dictionary, shall contain the Name key
~~~~

Imho it doesn't make much sense to add a verify method for this. ocgx2 should simply always add a /Name regardless of a standard, it shouldn't harm.

**Comment by u-fischer** [comment]
@agrahn new version on the way to ctan. You should be able to use the `\pdfmeta_standard_verify:nTF{Catalog_OCProperties_no_AS}` already now. If the property is not set/does not exist you get the true code from the test, and so what you have now.

**Comment by agrahn** [comment]
> I removed the requirement that suppressed the OCProperties Catalog entry for pdf/a-2 onwards.

@u-fischer : I tried with pdf/a-1a and `OCProperties` is also present while it shouldn't, according to veraPDF:
```

\DocumentMetadata{
  lang=en,pdfversion=1.7,
  pdfstandard=a-1a
}

\documentclass{article}

\usepackage{ocgx2}
\usepackage{lipsum}

\begin{document}
\begin{ocg}{lipsum-1}{lipsum1}{true}%
	\lipsum[1]
\end{ocg}%
\end{document}

```

**Comment by u-fischer** [comment]
well yes:

~~~~
Package pdf Warning: The standard 'A-1A' is unknown and has been ignored
~~~~

and the documentation (texdoc documentmetadata-support) says

> Currently A-1b, A-2a, A-2b, A-2u, A-3a, A-3b, A-3u, A-4, A-4E and A-4F are accepted as values

And no standard means everything is allowed.

**Comment by FrankMittelbach** [comment]
> well yes:
> 
> ```
> Package pdf Warning: The standard 'A-1A' is unknown and has been ignored
> ```
> 
> and the documentation (texdoc documentmetadata-support) says
> 
> > Currently A-1b, A-2a, A-2b, A-2u, A-3a, A-3b, A-3u, A-4, A-4E and A-4F are accepted as values
> 
> And no standard means everything is allowed.

I think it would be more appropriate if an unknown (or misspelled) standard generates an error, no?

**Comment by u-fischer** [comment]
> I think it would be more appropriate if an unknown (or misspelled) standard generates an error, no?

An unknown standard has been made an error in the latex-lab file, so I think the issue here can now be closed.
